/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 The documentation sidebar follows the Diataxis framework (https://diataxis.fr):
 tutorials teach, how-to guides solve a specific problem, explanation provides
 understanding, and reference (the separate sidebar below) describes the machinery.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentation: [
    'introduction',
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        description:
          'Lessons that take you through building a working deployment, start to finish. Follow them in order if you are new to PSAppDeployToolkit.',
      },
      collapsed: false,
      items: [
        'tutorials/your-first-deployment',
        'tutorials/adding-a-user-experience',
      ],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      link: {
        type: 'generated-index',
        description:
          'Recipes for specific goals, for when you already know what you want to achieve.',
      },
      collapsed: false,
      items: [
        'how-to/install-the-toolkit',
        'how-to/create-a-deployment',
        'how-to/run-a-deployment',
        'how-to/deploy-an-msi-with-zero-config',
        'how-to/install-applications',
        'how-to/close-apps-and-allow-deferral',
        'how-to/brand-the-user-interface',
        'how-to/customize-a-deployment',
        'how-to/extend-the-toolkit-with-custom-functions',
        'how-to/deploy-with-intune',
        'how-to/deploy-with-configmgr',
        'how-to/deploy-google-chrome-with-configmgr',
        'how-to/configure-with-group-policy',
        'how-to/set-the-log-path-with-group-policy',
        'how-to/troubleshoot-a-deployment',
        'how-to/upgrade-from-v4-0',
        'how-to/upgrade-from-v3',
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      link: {
        type: 'generated-index',
        description:
          'Background and reasoning, for when you want to understand why the toolkit behaves the way it does.',
      },
      collapsed: false,
      items: [
        'explanation/architecture',
        'explanation/the-deployment-script',
        'explanation/deployment-modes',
        'explanation/configuration',
        'explanation/logging',
        'explanation/user-interface',
      ],
    },
  ],
  reference: [
    'reference',
    'reference/requirements',
    'reference/deployment-template',
    'reference/module-structure',
    'reference/adtsession-object',
    'reference/command-line-parameters',
    'reference/variables',
    'reference/config-settings',
    'reference/language-strings',
    'reference/text-formatting',
    'reference/dialogs',
    'reference/exit-codes',
    'reference/troubleshooting',
    'reference/process-execution',
    'reference/v4-function-mapping',
    'reference/faq',
    'reference/release-notes',
    'reference/licensing',
    {
      type: 'category',
      label: 'Functions',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/functions', // generate sidebar from the docs folder (or versioned_docs/<version>)
        },
      ],
    },
  ],
};

export default sidebars;
