/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentation: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'getting-started/licensing',
        'getting-started/requirements',
        'getting-started/download',
        'getting-started/creating-a-new-deployment',
        'getting-started/release-notes',
        'getting-started/upgrade-guidance-4x-to-v41',
        'getting-started/upgrade-guidance-v3x-to-v41',
        'getting-started/faq',
      ],
    },
    {
      type: 'category',
      label: 'Deployment Concepts',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'deployment-concepts/deployment-structure',
        'deployment-concepts/invoke-appdeploytoolkit',
        'deployment-concepts/zero-config-deployment',
      ],
    },
    {
      type: 'category',
      label: 'Usage',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'usage/how-to-deploy',
        'usage/adding-ui-elements',
        'usage/customizing-deployments',
        'usage/installing-applications',
        'usage/admx-templates',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'examples/admxtemplate-LogPath' /*,
        'examples/googlechrome-configmgr'*/,
      ],
    },
  ],
  reference: [
    'reference',
    'reference/adtsession-object',
    'reference/variables',
    'reference/module-structure',
    'reference/config-settings',
    'reference/language-strings',
    'reference/text-formatting',
    'reference/exit-codes',
    'reference/v4-function-mapping',
    {
      type: 'category',
      label: 'Functions',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/functions', // generate sidebar from the docs folder (or versioned_docs/<version>)
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
